// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisGitCore
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisGitCore.4a9f479f-0aa0-4006-89d3-9073e4e1f978";
        public const string Name = "VisGitCore";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Steve Hall";
        public const string Tags = "";
    }
}
