// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisGit
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisGit.92e3f0ba-a8d6-4f83-a4da-e0da0d3722bb";
        public const string Name = "VisGit";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Steve Hall";
        public const string Tags = "";
    }
}
