// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisGit
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisGit.92e3f0ba-a8d6-4f83-a4da-e0da0d3722bb";
        public const string Name = "VisGit";
        public const string Description = @"VisGit allows you to view, edit and create Github Issues, Labels and Milestones from within Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mago Code";
        public const string Tags = "GitHub,Issues,Bug,Bugs,Milestone,Milestones,Labels";
    }
}
