// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisGit.Core
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisGit.Core.410a6b0d-db6a-48e7-bf59-abef3fd1df73";
        public const string Name = "VisGit.Core";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Steve Hall";
        public const string Tags = "";
    }
}
